### ISSUE TITLE
Consider using the generated code (EClasses) to obtain Stereotypes

### ISSUE THREAD

**Issue by abelgomez** [opendata-for-all/openapi-to-uml#13]
Now that the profile provide an EMF API (see https://github.com/opendata-for-all/openapi-profile/issues/2), it should be possible to obtain the Stereotypes from the generated Java code rather than hardcoding the Strings in the code.

See some examples in:

https://github.com/dice-project/DICE-Simulation/blob/f829c7b353aa7234c033553596e1330541df8023/bundles/es.unizar.disco.simulation.models/src/es/unizar/disco/simulation/models/definition/impl/CustomSimulationDefinitionImpl.java#L66

and

https://github.com/dice-project/DICE-Simulation/blob/master/bundles/es.unizar.disco.simulation.models/src/es/unizar/disco/simulation/models/util/MarteStereotypesUtils.java

**Comment by abelgomez** [comment]
This relates to #10 , where the stereotype is applied as `property.getApplicableStereotype("OpenAPIProfile::APIProperty")`

**Comment by hamzaed** [comment]
Thank you Abel for the tip. I'll give it a try. Indeed, using fully qualified names to retrieve stereotypes has limitations.
